routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');
Route::get('/template', 'PageController@template');
Route::get('/forget-password', function(){
  return view('frontend.login.forget-password');
})->name('forget-password');

Route::get('/referal-code/{usr}', 'PageController@referalLink')->name('referal');
// Route::get('/profile', 'PageController@profile');
// Route::get('/marketing-plan', 'PageController@marketingPlan');
// Route::get('/insurance', 'PageController@insurance');
// Route::get('/blog-news', 'PageController@blogNews');
// Route::get('/detail/{slug}', 'PageController@detail');
// Route::get('/contact-us', 'PageController@contact');
// Route::get('/test', 'PageController@test');
// Route::get('/stockist', 'PageController@stockist');
// Route::get('/album', 'PageController@album');
// Route::get('/gallery/{slug}', 'PageController@gallery');

// Route::get('/ilham/{id}', 'TestController@testIlham');
// Route::get('/test', 'TestController@test');
// Route::get('/closingDate', 'TestController@closingDate');
// Route::get('/autoWithdraw', 'TestController@autoWithdraw');
// Route::get('/checkMember', 'TestController@checkMember');

Route::prefix('admin')->name('admin.')->group(function () {
    // Route::get('/', 'Admin\LoginController')
    // Voyager::routes();
    Route::get('/login', 'Admin\LoginController@login')->name('login');
    Route::post('/login', 'Admin\LoginController@loginSubmit')->name('login.submit');
    Route::get('/logout', 'Admin\HomeController@logout')->name('logout');
    ROute::get('/test', 'Admin\HomeController@test')->name('test');

    Route::get('/clear-cache', function() {
        $exitCode = Artisan::call('config:clear');
        $exitCode = Artisan::call('cache:clear');
        $exitCode = Artisan::call('config:cache');
        return 'DONE';
    });

    Route::get('/', 'Admin\HomeController@index')->name('dashboard');
    Route::get('/fix-member-data', 'Admin\HomeController@fixMemberData')->name('fix_member_data');

    Route::prefix('blacklist-status')->name('blacklist_status')->group(function(){
      Route::get('/', 'Admin\BlacklistStatusController@index');
      Route::get('/new', 'Admin\BlacklistStatusController@new')->name('.new');
      Route::post('/new', 'Admin\BlacklistStatusController@create')->name('.create');
      Route::get('/edit/{id}', 'Admin\BlacklistStatusController@edit')->name('.edit');
      Route::post('/edit/{id}', 'Admin\BlacklistStatusController@update')->name('.update');
      Route::post('/delete', 'Admin\BlacklistStatusController@delete')->name('.delete');
    });

    Route::prefix('blacklist-member')->name('blacklist_member')->group(function(){
      Route::get('/', 'Admin\BlacklistMemberController@index');
      Route::get('/new', 'Admin\BlacklistMemberController@new')->name('.new');
      Route::post('/new', 'Admin\BlacklistMemberController@create')->name('.create');
      Route::post('/change-status', 'Admin\BlacklistMemberController@changeStatus')->name('.change_status');
    });

    Route::prefix('country')->name('country')->group(function(){
      Route::get('/', 'Admin\CountryController@index');
      Route::get('/new', 'Admin\CountryController@new')->name('.new');
      Route::post('/new', 'Admin\CountryController@create')->name('.create');
      Route::get('/edit/{id}', 'Admin\CountryController@edit')->name('.edit');
      Route::post('/edit/{id}', 'Admin\CountryController@update')->name('.update');
      Route::post('/delete', 'Admin\CountryController@delete')->name('.delete');
    });

    Route::prefix('character')->name('character.')->group(function(){
      Route::get('/', 'Admin\CharacterController@index');
      Route::get('/new', 'Admin\CharacterController@new')->name('new');
      Route::post('/new', 'Admin\CharacterController@create')->name('create');
      Route::get('/edit/{id}', 'Admin\CharacterController@edit')->name('edit');
      Route::post('/edit/{id}', 'Admin\CharacterController@update')->name('update');
      Route::post('/delete', 'Admin\CharacterController@delete')->name('delete');

      Route::prefix('show')->name('show')->group(function(){
        Route::get('download-template-order', 'Admin\CharacterController@downloadFormatTemplateOrder')->name('.download_template_order');
        Route::get('download-template-transaction', 'Admin\CharacterController@downloadFormatTemplateTransaction')->name('.download_template_transaction');
        Route::get('/{id}', 'Admin\CharacterController@show');
        Route::post('/{id}', 'Admin\CharacterController@showPost')->name('post');

        Route::post('order/set_status', 'Admin\CharacterController@charactersOrderStatus')->name('.order.set_status');

        Route::post('/{id}/export-order', 'Admin\CharacterController@exportOrder')->name('.export-order');
        Route::post('/{id}/export-seller', 'Admin\CharacterController@exportSeller')->name('.export-seller');
        Route::post('/{id}/import-order', 'Admin\CharacterController@importOrder')->name('.import-order');
        Route::post('/{id}/import-seller', 'Admin\CharacterController@importSeller')->name('.import-seller');
        Route::post('/{id}/import-transaction', 'Admin\CharacterController@importTransaction')->name('.import-transaction');
      });

      Route::prefix('transaction')->name('transaction')->group(function(){
        Route::get('/show/{id}', 'Admin\CharacterTransactionController@show')->name('.show');
        Route::get('/edit/{id}', 'Admin\CharacterTransactionController@edit')->name('.edit');
        Route::post('/edit/{id}', 'Admin\CharacterTransactionController@update')->name('.update');
        Route::get('/payment/show/{id}', 'Admin\CharacterTransactionController@showPayment')->name('.payment.show');
        Route::post('/set_status', 'Admin\CharacterTransactionController@changeStatus')->name('.set_status');
      });

      Route::get('/picture/{id}', 'Admin\CharacterController@showPicture')->name('picture.show');
    });

    Route::prefix('bank-company')->name('bank_company')->group(function(){
      Route::get('/', 'Admin\BankCompanyController@index');
      Route::get('/new', 'Admin\BankCompanyController@new')->name('.new');
      Route::post('/create', 'Admin\BankCompanyController@create')->name('.create');
      Route::get('/edit/{id}', 'Admin\BankCompanyController@edit')->name('.edit');
      Route::post('/edit/{id}', 'Admin\BankCompanyController@update')->name('.update');
      Route::post('/delete', 'Admin\BankCompanyController@delete')->name('.delete');
    });

    Route::prefix('bank')->name('bank')->group(function(){
      Route::get('/', 'Admin\BankController@index');
      Route::get('/new', 'Admin\BankController@new')->name('.new');
      Route::post('/create', 'Admin\BankController@create')->name('.create');
      Route::get('/edit/{id}', 'Admin\BankController@edit')->name('.edit');
      Route::post('/edit/{id}', 'Admin\BankController@update')->name('.update');
      Route::post('/delete', 'Admin\BankController@delete')->name('.delete');
    });

    Route::prefix('member')->name('member')->group(function(){
      Route::get('/', 'Admin\MemberController@index');
      Route::get('/show/{id}', 'Admin\MemberController@show')->name('.show');
      Route::get('/new', 'Admin\MemberController@new')->name('.new');
      Route::post('/new', 'Admin\MemberController@create')->name('.create');
      Route::get('/edit/{id}', 'Admin\MemberController@edit')->name('.edit');
      Route::post('/edit/{id}', 'Admin\MemberController@update')->name('.update');
      Route::post('/delete', 'Admin\MemberController@delete')->name('.delete');

      Route::post('/status', 'Admin\MemberController@setStatus')->name('.set_status');
    });

    Route::prefix('network')->name('network')->group(function(){
      Route::get('/', 'Admin\NetworkController@index');
    });

    Route::prefix('soul')->name('soul')->group(function(){
      Route::get('/', 'Admin\WalletController@soul');

      Route::prefix('buy')->name('.buy')->group(function(){
        Route::get('/', 'Admin\WalletController@soulBuy');
        Route::post('status', 'Admin\WalletController@soulSetStatus')->name('.set_status');
      });

      Route::prefix('transfer')->name('.transfer')->group(function(){
        Route::get('/', 'Admin\WalletController@soulTransfer');
        Route::get('/new', 'Admin\WalletController@soulTransferNew')->name('.new');
        Route::post('/create', 'Admin\WalletController@soulTransfer')->name('.create');
      });

      Route::get('/proof_of_payment/{id}', 'Admin\WalletController@imageProofOfPayment')->name('.image.proof_of_payment');
      Route::post('/proof_of_payment/upload', 'Admin\WalletController@uploadProofOfPayment')->name('.proof_of_payment.upload');
    });

    Route::prefix('setting')->name('setting')->group(function(){
      Route::get('/', 'Admin\SettingController@index');
      // Route::get('/new', 'Admin\SettingController@new')->name('.new');
      // Route::post('/new', 'Admin\SettingController@create')->name('.create');
      Route::get('/edit/{id}', 'Admin\SettingController@edit')->name('.edit');
      Route::post('/edit/{id}', 'Admin\SettingController@update')->name('.update');
    });

    Route::get('/profile', 'Admin\HomeController@profile')->name('profile');

    Route::get('jaringan', 'MemberController@index');
    Route::get('matching-member','Admin\MembersController@matching');
    Route::get('reset-match','Admin\MembersController@reset');
    Route::get('matching','Admin\MembersController@proses_matching');
    Route::get('get-username','Admin\TokenTransactionController@getUsername');

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Admin - Login</title>
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('') }}/img/apple-icon.png">
    <link rel="icon" type="image/png" href="{{ asset('') }}/img/favicon.png">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- CSS Files -->
    <link href="{{ asset('css/material-dashboard.css?v=2.1.1') }}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{{ asset('demo/demo.css') }}" rel="stylesheet" />
  </head>
  <body>
    <div class="container" style="height: auto;">
      <div class="message" style="margin-top: 20px">
        @include('flash::message')
      </div>
      <div class="row align-items-center">
        <div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">
          <form class="form" method="POST" action="{{ route('admin.login.submit') }}">
            {{ csrf_field() }}
            <div class="card card-login card-hidden mb-3">
              <div class="card-header card-header-primary text-center">
                <h4 class="card-title"><strong>{{ __('Login') }}</strong></h4>
              </div>
              <div class="card-body">
                <p class="card-description text-center">Hello, <strong>welcome</strong> you must login with your account. <strong>Keep Assemble</strong> </p>
                <div class="bmd-form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="material-icons">email</i>
                      </span>
                    </div>
                    <input type="email" name="email" class="form-control" placeholder="{{ __('Email...') }}" value="{{ old('email') }}" required>
                  </div>
                  @if ($errors->has('email'))
                    <div id="email-error" class="error text-danger pl-3" for="email" style="display: block;">
                      <strong>{{ $errors->first('email') }}</strong>
                    </div>
                  @endif
                </div>
                <div class="bmd-form-group{{ $errors->has('password') ? ' has-danger' : '' }} mt-3">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="material-icons">lock_outline</i>
                      </span>
                    </div>
                    <input type="password" name="password" id="password" class="form-control" placeholder="{{ __('Password...') }}" value="{{ !$errors->has('password') ? "" : "" }}" required>
                  </div>
                  @if ($errors->has('password'))
                    <div id="password-error" class="error text-danger pl-3" for="password" style="display: block;">
                      <strong>{{ $errors->first('password') }}</strong>
                    </div>
                  @endif
                </div>
                <div class="form-check mr-auto ml-3 mt-3">
                  <label class="form-check-label">
                    <input class="form-check-input" type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> {{ __('Remember me') }}
                    <span class="form-check-sign">
                      <span class="check"></span>
                    </span>
                  </label>
                </div>
              </div>
              <div class="card-footer justify-content-center">
                <button type="submit" class="btn btn-primary btn-link btn-lg">{{ __('Lets Go') }}</button>
              </div>
            </div>
          </form>
          <div class="row">
            <div class="col-6">
                @if (Route::has('password.request'))
                    <a href="{{ route('password.request') }}" class="text-light">
                        <small>{{ __('Forgot password?') }}</small>
                    </a>
                @endif
            </div>
            <div class="col-6 text-right">
                <a href="" class="text-light">
                    <small>{{ __('Create new account') }}</small>
                </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>